language: python

python:
  - "3.5"
before_install:
  - export DISPLAY=:99.0
  - export PYSPARK_PYTHON=python3.5
install:
  - ./install-spark.sh
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test --cov=Rollout TestRollout.py
after_success:
  coveralls